# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jp', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField()),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_death', models.DateTimeField(default='2150-10-25')),
                ('row1', models.TextField()),
                ('row2', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
