# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='operation',
            field=models.TextField(choices=[('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], default='INSERT'),
        ),
    ]
