# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181207_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_death',
            field=models.DateTimeField(default=datetime.datetime(2030, 6, 1, 13, 33)),
        ),
    ]
