# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181207_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(),
        ),
    ]
