# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181207_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
